use_frameworks!

target 'SKDesignableUIParts_Example' do
  pod 'SKDesignableUIParts', :path => '../'

  target 'SKDesignableUIParts_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
